version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/kunalwankhade
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/Kunal@1109
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Pre-build phase running..."

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."

  post_build:
    commands:
      - |
        aws ses send-email \
          --from "madithati123@gmail.com" \
          --to "madithati123@gmail.com" \
          --subject "CodeBuild Status: $CODEBUILD_BUILD_ID" \
          --text "Build status: $CODEBUILD_BUILD_STATUS" \
          --region "ap-south-1"

artifacts:
  files:
    - appspec.yaml